// <auto-generated />
using System;
using System.Collections.Generic;
using Conlang.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conlang.Infrastructure.Migrations
{
    [DbContext(typeof(ConlangDbContext))]
    [Migration("20230902071316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conlang.Core.Entities.IPA.IPASymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsVoiceless")
                        .HasColumnType("boolean");

                    b.Property<string>("MannerOfArticulation")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfArticulation")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IPASymbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Voiceless bilabial nasal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "m̥"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Voiced bilabial nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "m"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Voiceless bilabial plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "p"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Voiced bilabial plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "b"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Voiceless bilabial affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non-sibilant Affricate",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "pɸ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Voiced bilabial affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non-sibilant Affricate",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "bβ"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Voiceless bilabial fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "ɸ"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Voiced bilabial fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "β"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Voiceless bilabial fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "β̞"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Voiced bilabial flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "ⱱ̟"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Voiceless bilabial trill",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "ʙ̥"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Voiced bilabial trill",
                            IsVoiceless = false,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Bilabial",
                            Symbol = "ʙ"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Voiced Labiodental nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "ɱ"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Voiceless labiodental plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "p̪"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Voiced labiodental plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "b̪"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Voiceless labiodental affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Affricate",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "p̪f"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Voiced labiodental affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Affricate",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "b̪v"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Voiceless labiodental fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "f"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Voiced labiodental fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "v"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Voiced labiodental approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "ʋ"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Voiced labiodental flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Labiodental",
                            Symbol = "ⱱ"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Voiced linguolabial nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "n̼"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Voiceless linguolabial plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "t̼"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Voiced linguolabial plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "d̼"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Voiceless linguolabial fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "θ̼"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Voiced linguolabial fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "ð̼"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Voiced linguolabial plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Linguolabial",
                            Symbol = "ɾ̼"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Voiceless dental plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Dental",
                            Symbol = "t̪"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Voiced dental plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Dental",
                            Symbol = "d̪"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Voiceless dental affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Dental",
                            Symbol = "t̪s̪"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Voiced dental affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Dental",
                            Symbol = "d̪z̪"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Voiceless dental non-sibilant affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Dental",
                            Symbol = "t̪θ"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Voiced dental non-sibilant affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Dental",
                            Symbol = "d̪ð"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Voiceless dental fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Dental",
                            Symbol = "θ"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Voiced dental fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Dental",
                            Symbol = "ð"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Voiced dental approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Dental",
                            Symbol = "ð̞"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Voiced dental lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral approximant",
                            PlaceOfArticulation = "Dental",
                            Symbol = "l̪"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Voiceless alveolar lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral tap/flap",
                            PlaceOfArticulation = "Dental",
                            Symbol = "ɺ̥"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Voiceless alveolar nasal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "n̥"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Voiced alveolar nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "n"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Voiceless alveolar plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "t"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Voiced alveolar plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "d"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Voiceless alveolar affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ts"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Voiced alveolar affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "dz"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Voiceless alveolar non-sibilant affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "tɹ̝̊"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Voiced alveolar non-sibilant affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "dɹ̝"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Voiceless alveolar sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "s"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Voiced alveolar sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "z"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Voiceless alveolar non-sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "θ̠"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Voiced alveolar non-sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ð̠"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Voiced alveolar approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɹ"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Voiceless alveolar flap",
                            IsVoiceless = true,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɾ̥"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Voiced alveolar flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɾ"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Voiceless alveolar trill",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "r̥"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Voiced alveolar trill",
                            IsVoiceless = false,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "r"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Voiceless alveolar lateral affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "tɬ"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Voiced alveolar lateral affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "dɮ"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Voiceless alveolar lateral fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɬ"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Voiced alveolar lateral fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɮ"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Voiced alveolar lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "l"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Voiced alveolar lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Tap/flap",
                            PlaceOfArticulation = "Alveolar",
                            Symbol = "ɺ"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Voiceless postalveolar affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "t̠ʃ"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Voiced postalveolar affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "d̠ʒ"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Voiceless postalveolar non-sibilant affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "t̠ɹ̠̊˔"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Voiced postalveolar non-sibilant affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "d̠ɹ̠˔"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Voiceless postalveolar sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "ʃ"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Voiced postalveolar sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "ʒ"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Voiceless postalveolar non-sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "ɹ̠̊˔"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Voiced postalveolar non-sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "ɹ̠˔"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Voiced postalveolar approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "ɹ̠"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Voiced postalveolar trill",
                            IsVoiceless = false,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "r̠"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Voiced postalveolar lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Postalveolar",
                            Symbol = "l̠"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Voiceless retroflex nasal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɳ̊"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Voiced retroflex nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɳ"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Voiceless retroflex plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ʈ"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Voiced retroflex plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɖ"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Voiceless retroflex affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "tʂ"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Voiced retroflex affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "dʐ"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Voiceless retroflex sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ʂ"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Voiced retroflex sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ʐ"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Voiceless retroflex non-sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɻ̊˔"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Voiced retroflex non-sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɻ˔"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Voiced retroflex approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɻ"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Voiceless retroflex flap",
                            IsVoiceless = true,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɽ̊"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Voiced retroflex flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɽ"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Voiceless retroflex trill",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɽ̊r̥"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Voiced retroflex trill",
                            IsVoiceless = false,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɽr"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Voiceless retroflex lateral affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "tꞎ"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Voiced retroflex lateral affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɖ͡ɭ"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Voiceless retroflex lateral fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ꞎ"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Voiced retroflex lateral fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɭ̞̝"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Voiced retroflex lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɭ"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Voiceless retroflex lateral flap",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Tap/flap",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɭ̼̊"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Voiced retroflex lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Tap/flap",
                            PlaceOfArticulation = "Retroflex",
                            Symbol = "ɭ̺"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Voiceless palatal nasal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɲ̊"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Voiced palatal nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɲ"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Voiceless palatal plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "c"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Voiced palatal plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɟ"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Voiceless palatal affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "tɕ"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Voiced palatal affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "dʑ"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Voiceless palatal non-sibilant affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "cç"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Voiced palatal non-sibilant affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɟʝ"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Voiceless palatal sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɕ"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Voiced palatal sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Siblant Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʑ"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Voiceless palatal non-sibilant fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ç"
                        },
                        new
                        {
                            Id = 106,
                            Description = "Voiced palatal non-sibilant fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʝ"
                        },
                        new
                        {
                            Id = 107,
                            Description = "Voiced palatal approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "j"
                        },
                        new
                        {
                            Id = 108,
                            Description = "Voiceless palatal lateral affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "cʎ̥"
                        },
                        new
                        {
                            Id = 109,
                            Description = "Voiced palatal lateral affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ɟʎ̝"
                        },
                        new
                        {
                            Id = 110,
                            Description = "Voiceless palatal lateral fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʎ̥̞"
                        },
                        new
                        {
                            Id = 111,
                            Description = "Voiced palatal lateral fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʎ̝"
                        },
                        new
                        {
                            Id = 112,
                            Description = "Voiced palatal lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʎ"
                        },
                        new
                        {
                            Id = 113,
                            Description = "Voiced palatal lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Tap/flap",
                            PlaceOfArticulation = "Palatal",
                            Symbol = "ʎ̆"
                        },
                        new
                        {
                            Id = 114,
                            Description = "Voiceless velar nasal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ŋ̊"
                        },
                        new
                        {
                            Id = 115,
                            Description = "Voiced velar nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ŋ"
                        },
                        new
                        {
                            Id = 116,
                            Description = "Voiceless velar plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Velar",
                            Symbol = "k"
                        },
                        new
                        {
                            Id = 117,
                            Description = "Voiced velar plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Velar",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = 118,
                            Description = "Voiceless velar affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Velar",
                            Symbol = "kx"
                        },
                        new
                        {
                            Id = 119,
                            Description = "Voiced velar affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ɡɣ"
                        },
                        new
                        {
                            Id = 120,
                            Description = "Voiceless velar fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Velar",
                            Symbol = "x"
                        },
                        new
                        {
                            Id = 121,
                            Description = "Voiced velar fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ɣ"
                        },
                        new
                        {
                            Id = 122,
                            Description = "Voiced velar approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ɰ"
                        },
                        new
                        {
                            Id = 123,
                            Description = "Voiceless velar lateral affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Velar",
                            Symbol = "k𝼄"
                        },
                        new
                        {
                            Id = 124,
                            Description = "Voiced velar lateral affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Affricate",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ɡʟ̝"
                        },
                        new
                        {
                            Id = 125,
                            Description = "Voiceless velar lateral fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Velar",
                            Symbol = "𝼄"
                        },
                        new
                        {
                            Id = 126,
                            Description = "Voiced velar lateral fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Fricative",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ʟ̝"
                        },
                        new
                        {
                            Id = 127,
                            Description = "Voiced velar lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ʟ"
                        },
                        new
                        {
                            Id = 128,
                            Description = "Voiced velar lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Tap/flap",
                            PlaceOfArticulation = "Velar",
                            Symbol = "ʟ̆"
                        },
                        new
                        {
                            Id = 129,
                            Description = "Voiced uvular nasal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Nasal",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ɴ"
                        },
                        new
                        {
                            Id = 130,
                            Description = "Voiceless uvular plosive",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "q"
                        },
                        new
                        {
                            Id = 131,
                            Description = "Voiced uvular plosive",
                            IsVoiceless = false,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ɢ"
                        },
                        new
                        {
                            Id = 132,
                            Description = "Voiceless uvular affricate",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "qχ"
                        },
                        new
                        {
                            Id = 133,
                            Description = "Voiced uvular affricate",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ɢʁ"
                        },
                        new
                        {
                            Id = 134,
                            Description = "Voiceless uvular fricative",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "χ"
                        },
                        new
                        {
                            Id = 135,
                            Description = "Voiced uvular fricative",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ʁ"
                        },
                        new
                        {
                            Id = 136,
                            Description = "Voiced uvular approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ʁ̞"
                        },
                        new
                        {
                            Id = 137,
                            Description = "Voiced uvular lateral flap",
                            IsVoiceless = false,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ɢ̆"
                        },
                        new
                        {
                            Id = 138,
                            Description = "Voiceless uvular trill",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ʀ̥"
                        },
                        new
                        {
                            Id = 139,
                            Description = "Voiced uvular trill",
                            IsVoiceless = false,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ʀ"
                        },
                        new
                        {
                            Id = 140,
                            Description = "Voiced uvular lateral approximant",
                            IsVoiceless = false,
                            MannerOfArticulation = "Lateral Approximant",
                            PlaceOfArticulation = "Uvular",
                            Symbol = "ʟ̠"
                        },
                        new
                        {
                            Id = 141,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʡ"
                        },
                        new
                        {
                            Id = 142,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʡʜ"
                        },
                        new
                        {
                            Id = 143,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʡʢ"
                        },
                        new
                        {
                            Id = 144,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ħ"
                        },
                        new
                        {
                            Id = 145,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʕ"
                        },
                        new
                        {
                            Id = 146,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Tap/flap",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʡ̆"
                        },
                        new
                        {
                            Id = 147,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʜ"
                        },
                        new
                        {
                            Id = 148,
                            Description = "Pharyngeal/Epiglottal",
                            IsVoiceless = true,
                            MannerOfArticulation = "Trill",
                            PlaceOfArticulation = "Pharyngeal/Epiglottal",
                            Symbol = "ʢ"
                        },
                        new
                        {
                            Id = 149,
                            Description = "Glottal Stop",
                            IsVoiceless = true,
                            MannerOfArticulation = "Plosive",
                            PlaceOfArticulation = "Glottal",
                            Symbol = "ʔ"
                        },
                        new
                        {
                            Id = 150,
                            Description = "Glottal Stop",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Affricate",
                            PlaceOfArticulation = "Glottal",
                            Symbol = "ʔh"
                        },
                        new
                        {
                            Id = 151,
                            Description = "Glottal Stop",
                            IsVoiceless = true,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Glottal",
                            Symbol = "h"
                        },
                        new
                        {
                            Id = 152,
                            Description = "Glottal Stop",
                            IsVoiceless = false,
                            MannerOfArticulation = "Non Siblant Fricative",
                            PlaceOfArticulation = "Glottal",
                            Symbol = "ɦ"
                        },
                        new
                        {
                            Id = 153,
                            Description = "Glottal Stop",
                            IsVoiceless = true,
                            MannerOfArticulation = "Approximant",
                            PlaceOfArticulation = "Glottal",
                            Symbol = "ʔ̞"
                        });
                });

            modelBuilder.Entity("Conlang.Core.Entities.IPA.VowelSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<bool?>("Rounded")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VowelSymbols");

                    b.HasData(
                        new
                        {
                            Id = 154,
                            Description = "Close front unrounded vowel",
                            Height = "Close",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "i"
                        },
                        new
                        {
                            Id = 155,
                            Description = "Close front rounded vowel",
                            Height = "Close",
                            Position = "Front",
                            Rounded = true,
                            Symbol = "y"
                        },
                        new
                        {
                            Id = 156,
                            Description = "Close central unrounded vowel",
                            Height = "Close",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ɨ"
                        },
                        new
                        {
                            Id = 157,
                            Description = "Close central rounded vowel",
                            Height = "Close",
                            Position = "Central",
                            Rounded = true,
                            Symbol = "ʉ"
                        },
                        new
                        {
                            Id = 158,
                            Description = "Close back unrounded vowel",
                            Height = "Close",
                            Position = "Back",
                            Rounded = false,
                            Symbol = "ɯ"
                        },
                        new
                        {
                            Id = 159,
                            Description = "Close back rounded vowel",
                            Height = "Close",
                            Position = "Back",
                            Rounded = true,
                            Symbol = "u"
                        },
                        new
                        {
                            Id = 160,
                            Description = "Near-close near-front unrounded vowel",
                            Height = "Near-close",
                            Position = "Near-front",
                            Rounded = false,
                            Symbol = "ɪ"
                        },
                        new
                        {
                            Id = 161,
                            Description = "Near-close near-front rounded vowel",
                            Height = "Near-close",
                            Position = "Near-front",
                            Rounded = true,
                            Symbol = "ʏ"
                        },
                        new
                        {
                            Id = 162,
                            Description = "Near-close near-back rounded vowel",
                            Height = "Near-close",
                            Position = "Near-back",
                            Rounded = true,
                            Symbol = "ʊ"
                        },
                        new
                        {
                            Id = 163,
                            Description = "Close-mid front unrounded vowel",
                            Height = "Close-mid",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "e"
                        },
                        new
                        {
                            Id = 164,
                            Description = "Close-mid front rounded vowel",
                            Height = "Close-mid",
                            Position = "Front",
                            Rounded = true,
                            Symbol = "ø"
                        },
                        new
                        {
                            Id = 165,
                            Description = "Close-mid central unrounded vowel",
                            Height = "Close-mid",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ɘ"
                        },
                        new
                        {
                            Id = 166,
                            Description = "Close-mid central rounded vowel",
                            Height = "Close-mid",
                            Position = "Central",
                            Rounded = true,
                            Symbol = "ɵ"
                        },
                        new
                        {
                            Id = 167,
                            Description = "Close-mid back unrounded vowel",
                            Height = "Close-mid",
                            Position = "Back",
                            Rounded = false,
                            Symbol = "ɤ"
                        },
                        new
                        {
                            Id = 168,
                            Description = "Close-mid back rounded vowel",
                            Height = "Close-mid",
                            Position = "Back",
                            Rounded = true,
                            Symbol = "o"
                        },
                        new
                        {
                            Id = 169,
                            Description = "Mid front unrounded vowel",
                            Height = "Mid",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "e̞"
                        },
                        new
                        {
                            Id = 170,
                            Description = "Mid front rounded vowel",
                            Height = "Mid",
                            Position = "Front",
                            Rounded = true,
                            Symbol = "ø̞"
                        },
                        new
                        {
                            Id = 171,
                            Description = "Mid central vowel",
                            Height = "Mid",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ə"
                        },
                        new
                        {
                            Id = 172,
                            Description = "Mid back unrounded vowel",
                            Height = "Mid",
                            Position = "Back",
                            Rounded = false,
                            Symbol = "ɤ̞"
                        },
                        new
                        {
                            Id = 173,
                            Description = "Mid back rounded vowel",
                            Height = "Mid",
                            Position = "Back",
                            Rounded = true,
                            Symbol = "o̞"
                        },
                        new
                        {
                            Id = 174,
                            Description = "Open-mid front unrounded vowel",
                            Height = "Open-mid",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "ɛ"
                        },
                        new
                        {
                            Id = 175,
                            Description = "Open-mid front rounded vowel",
                            Height = "Open-mid",
                            Position = "Front",
                            Rounded = true,
                            Symbol = "œ"
                        },
                        new
                        {
                            Id = 176,
                            Description = "Open-mid central unrounded vowel",
                            Height = "Open-mid",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ɜ"
                        },
                        new
                        {
                            Id = 177,
                            Description = "Open-mid central rounded vowel",
                            Height = "Open-mid",
                            Position = "Central",
                            Rounded = true,
                            Symbol = "ɞ"
                        },
                        new
                        {
                            Id = 178,
                            Description = "Open-mid back unrounded vowel",
                            Height = "Open-mid",
                            Position = "Back",
                            Rounded = false,
                            Symbol = "ʌ"
                        },
                        new
                        {
                            Id = 179,
                            Description = "Open-mid back rounded vowel",
                            Height = "Open-mid",
                            Position = "Back",
                            Rounded = true,
                            Symbol = "ɔ"
                        },
                        new
                        {
                            Id = 180,
                            Description = "Near-open front unrounded vowel",
                            Height = "Near-open",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "æ"
                        },
                        new
                        {
                            Id = 181,
                            Description = "Near-open central vowel",
                            Height = "Near-open",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ɐ"
                        },
                        new
                        {
                            Id = 182,
                            Description = "Open front unrounded vowel",
                            Height = "Open",
                            Position = "Front",
                            Rounded = false,
                            Symbol = "a"
                        },
                        new
                        {
                            Id = 183,
                            Description = "Open front rounded vowel",
                            Height = "Open",
                            Position = "Front",
                            Rounded = true,
                            Symbol = "ɶ"
                        },
                        new
                        {
                            Id = 184,
                            Description = "Open central unrounded vowel",
                            Height = "Open",
                            Position = "Central",
                            Rounded = false,
                            Symbol = "ä"
                        },
                        new
                        {
                            Id = 185,
                            Description = "Open back unrounded vowel",
                            Height = "Open",
                            Position = "Back",
                            Rounded = false,
                            Symbol = "ɑ"
                        },
                        new
                        {
                            Id = 186,
                            Description = "Open back rounded vowel",
                            Height = "Open",
                            Position = "Back",
                            Rounded = true,
                            Symbol = "ɒ"
                        });
                });

            modelBuilder.Entity("Conlang.Core.Entities.Syllables.Coda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AllowedConsonantClusters")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AllowedFinalCoda")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AllowedInitialCoda")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AllowedInternalCoda")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Coda");
                });

            modelBuilder.Entity("Conlang.Core.Entities.Syllables.Nucleus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AllowedSyllables")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Diphthongs")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Vowels")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Nucleus");
                });

            modelBuilder.Entity("Conlang.Core.Entities.Syllables.Onset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AllowedFinalOnset")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AllowedInitialOnset")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AllowedInternalOnset")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Onset");
                });

            modelBuilder.Entity("Conlang.Core.Entities.Syllables.Syllable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodaComponentId")
                        .HasColumnType("integer");

                    b.Property<int?>("NucleusComponentId")
                        .HasColumnType("integer");

                    b.Property<int?>("OnsetComponentId")
                        .HasColumnType("integer");

                    b.Property<int?>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodaComponentId");

                    b.HasIndex("NucleusComponentId");

                    b.HasIndex("OnsetComponentId");

                    b.HasIndex("WordId");

                    b.ToTable("Syllable");
                });

            modelBuilder.Entity("Conlang.Core.Words.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnglishTranslation")
                        .HasColumnType("text");

                    b.Property<string>("IPARepresentation")
                        .HasColumnType("text");

                    b.Property<string>("Latinization")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Register")
                        .HasColumnType("integer");

                    b.Property<int[]>("Types")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Conlang.Core.Entities.Syllables.Syllable", b =>
                {
                    b.HasOne("Conlang.Core.Entities.Syllables.Coda", "CodaComponent")
                        .WithMany()
                        .HasForeignKey("CodaComponentId");

                    b.HasOne("Conlang.Core.Entities.Syllables.Nucleus", "NucleusComponent")
                        .WithMany()
                        .HasForeignKey("NucleusComponentId");

                    b.HasOne("Conlang.Core.Entities.Syllables.Onset", "OnsetComponent")
                        .WithMany()
                        .HasForeignKey("OnsetComponentId");

                    b.HasOne("Conlang.Core.Words.Word", null)
                        .WithMany("Syllables")
                        .HasForeignKey("WordId");

                    b.Navigation("CodaComponent");

                    b.Navigation("NucleusComponent");

                    b.Navigation("OnsetComponent");
                });

            modelBuilder.Entity("Conlang.Core.Words.Word", b =>
                {
                    b.Navigation("Syllables");
                });
#pragma warning restore 612, 618
        }
    }
}
